enum MIRRORING
{
    MIRROR_HORIZONTAL=0,
    MIRROR_VERTICAL=1,
    MIRROR_FOURSCREEN,
    MIRROR_SINGLESCREEN,
    MIRROR_MAX=MIRROR_SINGLESCREEN
};

enum ROMCONTROL1 {
    RCTL1_VERTICALM=0x1,
    RCTL1_BATTERYPACK=0x2,
    RCTL1_TRAINER=0x4,
    RCTL1_FOURSCREEN=0x8,
    RCTL1_MAPPERLOW=0xF0
};

enum ROMCONTROL2 {
    RCTL2_RESERVED=0xF,
    RCTL2_MAPPERHIGH=0xF0
};

extern MIRRORING /*ENUM<uint32_t,MIRRORING,MIRROR_MAX>*/ mirroring;
extern FLAG<uint8_t,ROMCONTROL1> RomCtrl;
extern FLAG<uint8_t,ROMCONTROL2> RomCtrl2;
